apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    app: ecommerce-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-mysql
  template:
    metadata:
      labels:
        app: ecommerce-mysql
    spec:
      containers:
      - name: mysql
        image: devopsdeepdive/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password123
        ports:
        - containerPort: 3306
