apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: ecommerce-frontend
spec:
  containers:
  - name: frontend
    image: devopsdeepdive/ecommerce-3tier_frontend
    ports:
    - containerPort: 80
